### ISSUE TITLE
Does not work With Update 5

### ISSUE THREAD

**Issue by spidey1958** [Turtlefight/SatisfactoryFasterManualCrafting#1]
The Mod does not currently work with Update 5

**Comment by Trxnsient** [comment]
I was just about to make my own issue. I forked it and tried to import into visual studio. My PC not very good so visual studio not responding, and I don't know much c++ unfortunately So maybe I not the best person to fork HAHA

**Comment by Turtlefight** [comment]
Hi, sorry last week has been a bit busy for me so i didn't manage to update it for the U5 Release.
I've updated it now for U5, Version 1.0.3 of Faster Manual Crafting should work now on EA & EXP :)
